# Generated by Django 6.0.4 on 2026-04-21 01:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la operación (debe ser positivo).', max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó la operación.')),
                ('tipo_operacion', models.CharField(choices=[('deposito', 'Depósito'), ('retiro', 'Retiro')], default='deposito', help_text='Tipo de operación: depósito o retiro.', max_length=20)),
                ('saldo_resultante', models.DecimalField(decimal_places=2, editable=False, help_text='Saldo de la cuenta después de aplicar la operación.', max_digits=14)),
                ('descripcion', models.CharField(blank=True, default='', help_text='Descripción opcional de la operación.', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='banking.cuentabancaria')),
            ],
            options={
                'verbose_name': 'Depósito / Movimiento',
                'verbose_name_plural': 'Depósitos / Movimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
