# Generated by Django 6.0.4 on 2026-04-20 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrantes', to='banking.cuentabancaria')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salientes', to='banking.cuentabancaria')),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('deposito', 'Depósito'), ('retiro', 'Retiro'), ('transferencia_origen', 'Transferencia (origen)'), ('transferencia_destino', 'Transferencia (destino)')], max_length=40)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_resultante', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='banking.cuentabancaria')),
                ('transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='banking.transferencia')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['cuenta', '-fecha'], name='banking_mov_cuenta__8804ab_idx')],
            },
        ),
    ]
