# Generated by Django 6.0.4 on 2026-04-21 01:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_deposito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto a transferir (debe ser positivo).', max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('descripcion', models.CharField(blank=True, default='', help_text='Concepto o descripción de la transferencia.', max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó la transferencia.')),
                ('estado', models.CharField(choices=[('exitosa', 'Exitosa'), ('fallida', 'Fallida')], default='exitosa', help_text='Estado final de la transferencia.', max_length=20)),
                ('saldo_origen_resultante', models.DecimalField(decimal_places=2, editable=False, help_text='Saldo de la cuenta origen después de la transferencia.', max_digits=14)),
                ('saldo_destino_resultante', models.DecimalField(decimal_places=2, editable=False, help_text='Saldo de la cuenta destino después de la transferencia.', max_digits=14)),
                ('cuenta_destino', models.ForeignKey(help_text='Cuenta que recibe el dinero.', on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recibidas', to='banking.cuentabancaria')),
                ('cuenta_origen', models.ForeignKey(help_text='Cuenta desde la que se envía el dinero.', on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='banking.cuentabancaria')),
                ('movimiento_destino', models.OneToOneField(blank=True, help_text='Movimiento (depósito) registrado en la cuenta destino.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencia_como_destino', to='banking.deposito')),
                ('movimiento_origen', models.OneToOneField(blank=True, help_text='Movimiento (retiro) registrado en la cuenta origen.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencia_como_origen', to='banking.deposito')),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-fecha'],
            },
        ),
    ]
